'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Grades
    Public Property Id As Integer
    Public Property Assessment As String
    Public Property Comments As String
    Public Property AssessmentDate As Date
    Public Property SubjectId As Integer
    Public Property StudentUserId As System.Guid

    Public Overridable Property Students As Students
    Public Overridable Property Subjects As Subjects

End Class
