'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class SchoolGradesDBEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=SchoolGradesDBEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Grades() As DbSet(Of Grades)
    Public Overridable Property Students() As DbSet(Of Students)
    Public Overridable Property Subjects() As DbSet(Of Subjects)
    Public Overridable Property Teachers() As DbSet(Of Teachers)
    Public Overridable Property Users() As DbSet(Of Users)

End Class
